config/routes.rb
Rails.application.routes.draw do

  
  get 'process/process_data'

  get 'process/search'

  post 'user/create'

  post 'user/edit'

  get 'user/username_availability'

  get 'user/view'

  get 'user/new'

  get 'user/settings'

  get 'user/login'

  post 'user/login'

  get 'user/logout'
  
  get "/check_thresholds" => "services#check_thresholds"
  
  get "/process_queued_sites" => "services#process_queued_sites"
  
  post 'check_site_code' => "services#check_site_code"

  get '/map' => "administration#map"
  
  get '/national_map' => "administration#national_map"
  
  get '/sync_map' => "administration#sync_map"
  
  get '/region/:id' => "administration#regional_map"
  
  get "/search_by_site_code/:id" => "services#search_by_site_code"

  post "/assign_npids_to_region" => "administration#assign_npids_to_region"

  post "/assign_npids_to_site" => "administration#assign_npids_to_site"

  get "/check_region_allocation" => "services#check_region_allocation"

  get "/check_site_allocation" => "services#check_site_allocation"

  get "/search_for_patients_by_site" => "services#search_for_patients_by_site"

  get 'administration/connection_add'

  get 'administration/connection_edit'

  get 'administration/connection_show'
  
  post 'administration/connection_create'

  post 'administration/connection_update'

  get '/check_duplicate_connections' => "services#check_duplicate_connections"

  get '/username_available' => "services#username_available"

  get '/process_data' => "process#process_data"

  post '/process_data' => "process#process_data"

  get '/search' => "process#search"

  post '/search' => "process#search"

  post '/process_confirmation' => "process#process_confirmation"

  post '/ajax_process_data' => "process#ajax_process_data"

  post '/lost' => "process#lost"

  get '/administration/search' => "administration#search"

  get '/ajax_search' => "administration#ajax_search"

  get '/footprint' => "administration#footprint"

  post '/ajax_log' => "process#ajax_log"

  get '/dashboard' => "dashboard#dual_display"

  get '/dashboard_old' => "dashboard#dashboard"

  get '/dashboard_person' => "dashboard#person_map"

  get '/dashboard_npids' => "dashboard#npids_map"

  get '/ajax_connections' => "dashboard#ajax_connections"

  get '/ajax_person_connections' => "dashboard#ajax_person_connections"

  get '/ajax_npids_distribution' => "dashboard#ajax_npids_distribution"

  get '/dashboard_npids_distribution' => "dashboard#npids_distribution"

  get '/dashboard_burdens' => "dashboard#burdens"

  get '/ajax_burdens' => "dashboard#ajax_burdens"

  get '/ajax_movements' => "dashboard#ajax_movements"

  get '/dashboard_movements' => "dashboard#movements"
  
  post '/merge_duplicates' => "process#merge_duplicates"

  namespace :ws do
    namespace :rest do
      resources :v1 do
        
        collection do
          get :active_tasks
        end
        
      end
    end
  end

  resources :people do
    collection do
      post :find, :create, :create_footprint, :update_person, :find_demographics, :update_demographics
      get :find, :confirm_demographics 
    end
  end

  resource :login do
    collection do
      get :logout
    end
  end	

  resources :administration do 
    collection  do
		  post :create_site, :update_site
		  get :index, :site_add, :site_edit, :site_show, :site_assign, :region_edit,:region_show 
    end
  end

																																														

  root :to => 'logins#show'

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  skip_before_filter :perform_basic_auth, :only => :logout

  def show
    # render
  end

  def create
    username = params[:user][:username]
    password = params[:user][:password]
    user = Utils::UserUtil.get_active_user(username)
    if user and user.password_matches?(password)
      login! user
      redirect_to back_or_default
    else
      flash[:error] = 'That username and/or password was not valid.'
      render :action => 'show'
    end
  end

  def logout
    logout!
    flash[:notice] = 'You have been logged out. Good Bye!'
    redirect_to :action => 'show', referrer_param => referrer_path
  end

  protected

  def default_path
    '/administration'
  end

  def perform_basic_auth
    authorize! :access, :login
  end

  def access_denied
    redirect_to default_path
  end

end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/show.html.erb
<style>

body
{
    background-color: #1b1b1b;
    padding-top: 40px;
}


.input-group-addon
{
    background-color: rgb(50, 118, 177);
    border-color: rgb(40, 94, 142);
    color: rgb(255, 255, 255);
}
.form-control:focus
{
    background-color: #eee;
    color: #000;
}

.form-signup input  { border: 1px solid rgb(50, 118, 177); }

</style>

<br />
<br />
<br />
<br />
<br />


<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <h5 class="text-center">DDE 2</h5>
          <%= form_tag(login_path, method: 'post', enctype: 'multipart/form-data', class: 'form form-signup', autocomplete: "off") do %>
            <%= hidden_referrer_input_tag %>
            <div class="form-group">
              <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                <%=text_field(:user, :username, :textCase => "lower",:placeholder => "username",:class => 'form-control') %>
              </div>
            </div>
            <div class="form-group">
              <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                <%=password_field(:user, :password, :textCase => "lower",:placeholder => "password",:class => 'form-control') %>
              </div>
            </div>
          </div>
          <%= submit_tag "Login" ,:class => "btn btn-primary btn-block" , 
              :role => "button", :style => "margin: auto !important; width: 40% !important; 
              margin-bottom: 20px !important; height: 40px !important;" %>
        <%end%>
      </div>
    </div>
  </div>
</div>
</div> 